export enum UserRole {
  USER = 'USER',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  MODERATOR = 'MODERATOR',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum RiskLevel {
  SAFE = 'SAFE',
  LOW_RISK = 'LOW_RISK',
  CAUTION = 'CAUTION',
  LIKELY_SPAM = 'LIKELY_SPAM',
  HIGH_RISK = 'HIGH_RISK',
}

export enum CallerCategory {
  PERSONAL = 'PERSONAL',
  BUSINESS = 'BUSINESS',
  DELIVERY = 'DELIVERY',
  BANK = 'BANK',
  PAYMENT_UPI = 'PAYMENT_UPI',
  LOAN_FINANCE = 'LOAN_FINANCE',
  INSURANCE = 'INSURANCE',
  CREDIT_CARD_SALES = 'CREDIT_CARD_SALES',
  TELEMARKETING = 'TELEMARKETING',
  REAL_ESTATE = 'REAL_ESTATE',
  JOB_RECRUITMENT = 'JOB_RECRUITMENT',
  SCHOOL_EDUCATION = 'SCHOOL_EDUCATION',
  HOSPITAL_CLINIC = 'HOSPITAL_CLINIC',
  GOVERNMENT = 'GOVERNMENT',
  UTILITY_SERVICES = 'UTILITY_SERVICES',
  COURIER = 'COURIER',
  CAB_RIDE_SHARING = 'CAB_RIDE_SHARING',
  ECOMMERCE = 'ECOMMERCE',
  POLITICAL_CAMPAIGN = 'POLITICAL_CAMPAIGN',
  SURVEY = 'SURVEY',
  FRAUD = 'FRAUD',
  SCAM = 'SCAM',
  HARASSMENT = 'HARASSMENT',
  SPAM = 'SPAM',
  UNKNOWN = 'UNKNOWN',
}

export enum ReportType {
  SPAM = 'SPAM',
  FRAUD = 'FRAUD',
  SCAM = 'SCAM',
  HARASSMENT = 'HARASSMENT',
  TELEMARKETING = 'TELEMARKETING',
  ROBOCALL = 'ROBOCALL',
  SILENT_CALL = 'SILENT_CALL',
  FAKE_BANK = 'FAKE_BANK',
  OTP_SCAM = 'OTP_SCAM',
  PAYMENT_SCAM = 'PAYMENT_SCAM',
  JOB_SCAM = 'JOB_SCAM',
  SAFE = 'SAFE',
  WRONG_NUMBER = 'WRONG_NUMBER',
}

export enum VerificationType {
  NONE = 'NONE',
  COMMUNITY = 'COMMUNITY',
  DOCUMENT = 'DOCUMENT',
  ADMIN = 'ADMIN',
  OFFICIAL = 'OFFICIAL',
}

export enum SourceType {
  COMMUNITY = 'COMMUNITY',
  ADMIN = 'ADMIN',
  OFFICIAL = 'OFFICIAL',
  BUSINESS_CLAIM = 'BUSINESS_CLAIM',
  UNKNOWN = 'UNKNOWN',
}

export enum AdminOverrideStatus {
  NONE = 'NONE',
  CONFIRMED_FRAUD = 'CONFIRMED_FRAUD',
  VERIFIED_SAFE = 'VERIFIED_SAFE',
  UNDER_REVIEW = 'UNDER_REVIEW',
}

export enum DisputeStatus {
  NONE = 'NONE',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum BusinessVerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum DisputeType {
  WRONG_LABEL = 'WRONG_LABEL',
  WRONG_CATEGORY = 'WRONG_CATEGORY',
  PERSONAL_NUMBER = 'PERSONAL_NUMBER',
  BUSINESS_NUMBER = 'BUSINESS_NUMBER',
  OTHER = 'OTHER',
}

export enum AppTheme {
  CRYSTAL_GLASS = 'CRYSTAL_GLASS',
  MIDNIGHT_TRUST = 'MIDNIGHT_TRUST',
  CLEAN_LIGHT = 'CLEAN_LIGHT',
  HIGH_CONTRAST = 'HIGH_CONTRAST',
  TRUE_SIGNAL = 'TRUE_SIGNAL',
}

export enum Platform {
  ANDROID = 'ANDROID',
  WEB = 'WEB',
  ADMIN = 'ADMIN',
}
