const fs = require('fs');
const path = require('path');

const distDir = path.join(__dirname, '..', 'dist');

const css = `/* ClearRing UI Tokens — generated by build-css.js */

:root {
  /* Brand */
  --cr-primary: #6366f1;
  --cr-primary-dark: #4f46e5;
  --cr-primary-light: #a5b4fc;
  --cr-secondary: #8b5cf6;
  --cr-accent: #06b6d4;

  /* Risk levels */
  --cr-risk-safe: #22c55e;
  --cr-risk-low: #eab308;
  --cr-risk-caution: #f97316;
  --cr-risk-likely-spam: #ef4444;
  --cr-risk-high: #dc2626;
  --cr-risk-verified: #3b82f6;
  --cr-risk-unknown: #6b7280;

  /* Spacing */
  --cr-space-1: 4px;
  --cr-space-2: 8px;
  --cr-space-3: 12px;
  --cr-space-4: 16px;
  --cr-space-6: 24px;
  --cr-space-8: 32px;
  --cr-space-12: 48px;
  --cr-space-16: 64px;

  /* Typography */
  --cr-font-sans: 'Inter', system-ui, -apple-system, sans-serif;
  --cr-font-mono: 'JetBrains Mono', 'Fira Code', monospace;
  --cr-text-xs: 0.75rem;
  --cr-text-sm: 0.875rem;
  --cr-text-base: 1rem;
  --cr-text-lg: 1.125rem;
  --cr-text-xl: 1.25rem;
  --cr-text-2xl: 1.5rem;
  --cr-text-3xl: 1.875rem;
  --cr-text-4xl: 2.25rem;
  --cr-font-normal: 400;
  --cr-font-medium: 500;
  --cr-font-semibold: 600;
  --cr-font-bold: 700;
  --cr-font-black: 900;
}

/* Theme: Crystal Glass */
[data-theme="CRYSTAL_GLASS"] {
  --cr-bg: linear-gradient(135deg, #667eea 0%, #764ba2 50%, #06b6d4 100%);
  --cr-bg-secondary: rgba(99,102,241,0.15);
  --cr-surface: rgba(255,255,255,0.12);
  --cr-surface-hover: rgba(255,255,255,0.18);
  --cr-border: rgba(255,255,255,0.25);
  --cr-text: #ffffff;
  --cr-text-secondary: rgba(255,255,255,0.85);
  --cr-text-muted: rgba(255,255,255,0.6);
  --cr-blur: blur(16px);
  --cr-shadow: 0 8px 32px rgba(0,0,0,0.2);
}

/* Theme: Midnight Trust */
[data-theme="MIDNIGHT_TRUST"] {
  --cr-bg: linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0c1a3a 100%);
  --cr-bg-secondary: #1e293b;
  --cr-surface: rgba(30,41,59,0.9);
  --cr-surface-hover: rgba(51,65,85,0.9);
  --cr-border: rgba(148,163,184,0.15);
  --cr-text: #f1f5f9;
  --cr-text-secondary: #94a3b8;
  --cr-text-muted: #64748b;
  --cr-blur: blur(12px);
  --cr-shadow: 0 8px 32px rgba(0,0,0,0.4);
}

/* Theme: Clean Light */
[data-theme="CLEAN_LIGHT"] {
  --cr-bg: #f8fafc;
  --cr-bg-secondary: #f1f5f9;
  --cr-surface: #ffffff;
  --cr-surface-hover: #f8fafc;
  --cr-border: #e2e8f0;
  --cr-text: #0f172a;
  --cr-text-secondary: #334155;
  --cr-text-muted: #64748b;
  --cr-blur: none;
  --cr-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

/* Theme: High Contrast */
[data-theme="HIGH_CONTRAST"] {
  --cr-bg: #000000;
  --cr-bg-secondary: #1a1a1a;
  --cr-surface: #1a1a1a;
  --cr-surface-hover: #2a2a2a;
  --cr-border: #ffffff;
  --cr-text: #ffffff;
  --cr-text-secondary: #ffff00;
  --cr-text-muted: #cccccc;
  --cr-blur: none;
  --cr-shadow: 0 0 0 2px #ffffff;
}

/* Theme: True Signal */
[data-theme="TRUE_SIGNAL"] {
  --cr-bg: linear-gradient(135deg, #064e3b 0%, #065f46 50%, #0e7490 100%);
  --cr-bg-secondary: rgba(6,78,59,0.3);
  --cr-surface: rgba(255,255,255,0.1);
  --cr-surface-hover: rgba(255,255,255,0.16);
  --cr-border: rgba(52,211,153,0.3);
  --cr-text: #ecfdf5;
  --cr-text-secondary: rgba(236,253,245,0.85);
  --cr-text-muted: rgba(236,253,245,0.6);
  --cr-blur: blur(12px);
  --cr-shadow: 0 8px 32px rgba(0,0,0,0.25);
}

/* Risk badge utility classes */
.cr-risk-safe     { background: #22c55e; color: #fff; }
.cr-risk-low      { background: #eab308; color: #fff; }
.cr-risk-caution  { background: #f97316; color: #fff; }
.cr-risk-spam     { background: #ef4444; color: #fff; }
.cr-risk-high     { background: #dc2626; color: #fff; }
.cr-risk-verified { background: #3b82f6; color: #fff; }
.cr-risk-unknown  { background: #6b7280; color: #fff; }
`;

fs.writeFileSync(path.join(distDir, 'tokens.css'), css, 'utf8');
console.log('✓ dist/tokens.css generated');
